messages:
  noPermission: "&cУ вас нет разрешения!"
  reloaded: "&aПлагин успешно перезагружен!"
  newPos: "&aВы успешно установили позицию №{0}!"
  noConsole: "&cНельзя выполнить эту команду от лица консоли!"
  blockIsEmpty: "&cПосмотрите на блок для установки!"
  mineIsLocked: "&cШахта еще закрыта!"
blocked_level_item:
  material: BARRIER
  displayName: '[display_name]'
  lore:
    - " "
    - "{S}Статус: &cЗакрыто"
    - "{S}Вскопано блоков: {M}%flamemine_mines% / [need]"
    - " "
settings:
  action_in_upgrade_mine: NEXT # или RANDOM
  update_time: 600 # раз в сколько секунд обновлять шахту?
  respawnLocation:
    x: 0
    y: 10
    z: 0
    world: world
  hologram:
    position:
      x: 0
      y: 0
      z: 0
      world: world
    lines:
      - Material.NETHERITE_PICKAXE
      - "{M}%flamemine_now_mine%"
      - "{S}До обновления: {M}%flamemine_timer%"
levels:
  id0:
    name: "{S}Слабая шахта"
    requirements:
      needMineBlocks: false
      amount: 0
    ores:
      COBBLESTONE: 90.0
      IRON_ORE: 45.0
      GOLD_ORE: 30.0
  id1:
    name: "{S}Неплохая шахта"
    requirements:
      needMineBlocks: true
      amount: 4000
    ores:
      COBBLESTONE: 80.0
      IRON_ORE: 50.0
      GOLD_ORE: 35.0
      DIAMOND_ORE: 15.0
  id2:
    name: "{S}Нормальная шахта"
    requirements:
      needMineBlocks: true
      amount: 8000
    ores:
      COBBLESTONE: 70.0
      IRON_ORE: 55.0
      GOLD_ORE: 38.0
      DIAMOND_ORE: 20.0
      EMERALD_ORE: 12.0
  id3:
    name: "{S}Сильная шахта"
    requirements:
      needMineBlocks: true
      amount: 15000
    ores:
      COBBLESTONE: 60.0
      IRON_ORE: 50.0
      GOLD_ORE: 40.0
      DIAMOND_ORE: 25.0
      EMERALD_ORE: 15.0
      ANCIENT_DEBRIS: 9.0
  id4:
    name: "{S}Адская шахта"
    requirements:
      needMineBlocks: true
      amount: 25000
    ores:
      NETHERRACK: 80.0
      NETHER_QUARTZ_ORE: 60.0
      NETHER_GOLD_ORE: 55.0
      ANCIENT_DEBRIS: 15.0