name: FlameMine
version: '1.0.2'
main: org.satellite.dev.progiple.flamemine.FlameMine
api-version: '1.16'
authors: [NovaSparkle]
depend:
  - LunaSpring
  - DecentHolograms
  - PlaceholderAPI
commands:
  flamemine:
    aliases:
      - fm
      - fmine
      - mine
      - flamem
permissions:
  flamemine.admin:
    default: op